version: '2'
services:
    smsbulkcampaignsender-app:
        image: smsbulkcampaignsender
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smsbulkcampaignsender-mysql:3306/smsbulkcampaignsender?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smsbulkcampaignsender-mysql:
        extends:
            file: mysql.yml
            service: smsbulkcampaignsender-mysql
